### ISSUE TITLE
Не работает локальное переопределение шаблона

### ISSUE THREAD

**Issue by villanella** [SEAFTeam/seaf-dzo-example#30]
Структура репозитория:
```
/dochub.yaml 
/templates-test/blank2.md
/_metamodel_  - тут готовая метамодель SEAF
/файлы архитектуры
```

В  dochub.yaml переопределен шаблон для ADR:
```
entities:                            
  seaf.change.adr:
    presentations:
      blank:
        template: templates-test/blank2.md
```
Путь к шаблону подставляется относительно метамодели, а не корневой, поэтому ошибка:

```
Источник: /entities/seaf.change.adr/presentations/blank
Ошибка:"No found: plugin:/idea/source/_metamodel_/seaf-core/entities/change/adr/templates-test/blank2.md?id=blank&path=/entities/seaf.change.adr/presentations/blank"
```
